### ISSUE TITLE
Attempting to edit and save an experiment with the name of an existing one, wrongly links the existing experiment on top of the page and hitting cancel redirects you to it

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/experimenter#1127]
**[Affected versions]:**
- Firefox 66.0.2 and up
- Chrome Version 73.0

**[Affected Platforms]:**
- All Mac
- All Windows
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have at least 2 experiments created on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser and navigate to one of the experiments from prerequisites.
2. Click the “Edit” button from the “Overview” section.
3. Scroll to the “Name” field and replace the name of the experiment with one of an existing experiment.
4. Click the “Save Draft” button and observe the title of the experiment.
5. Click the “Cancel Editing” button and observe the behavior.

**[Expected result]:**
Step 4. The title of the experiment does not change.
Step 5. You are redirected to the main page of the edited experiment.

**[Actual result]:**
Step 4. The title of the edited experiment is updated with the title of the existing one.
Step 5. You are redirected to the main page of the existing experiment instead of the edited one.

**[Notes]:**
- This issue is also reproducible when creating a new experiment. 
- Clicking the title after attempting to save an experiment with the name of another existing one, redirects you to the main page of the existing experiment. 
- Attached a screen recording with the issue:

![rec of issue - renaming an experiment](https://user-images.githubusercontent.com/37875464/55170244-def77800-517e-11e9-8bff-32dea5148722.gif)

**Comment by jaredkerim** [comment]
I think this should be fixed when we fix https://github.com/mozilla/experimenter/issues/1129 but I'll leave this open to validate after I land the fix for it.

**Comment by jaredkerim** [comment]
Actually I'll do the opposite, I'll close this as fixed by #1129 and if it's not fixed we can reopen it.

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue on the https://stage.experimenter.nonprod.dataops.mozgcp.net website on Windows 10 x64, Mac 10.14 and Arch Linux, and it is partially fixed. Canceling the edit no longer redirects to the main page of the existing experiment instead of the edited one. 

However, when attempting to save the experiment with the name of a preexisting one, the title of the edited experiment will change despite the "!Experiment with this Name already exists" error being displayed.

Attached a screen recording with the issue:

![rec of issue -  title name](https://user-images.githubusercontent.com/37875464/56645818-10346c80-6687-11e9-9452-4fbae037c365.gif)


Considering this I will reopen this issue.

**Comment by jaredkerim** [comment]
I'm going to bump this out of 2.28 and into 2.29 because I don't think it's a critical blocker for 2.28.

**Comment by shell1** [comment]
Remove the link that gets busted.  Not at all needed.

**Comment by jaredkerim** [comment]
We have to revert this: https://github.com/mozilla/experimenter/issues/1099

**Comment by jaredkerim** [comment]
Oh I see what's going on, the link points to the correct place, it's just labeled with the new (invalid) name instead of the old one.  I don't think there's an easy way to fix that, and it doesn't actually break any of the logic it just looks a little confusing so I vote this is a wontfix.  @shell1 what do you think?

**Comment by jaredkerim** [comment]
From @shell1 on slack we will close this as a wontfix.
