### ISSUE TITLE
Some older experiments show a 500 error code when trying to access their History page

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#9553]
**[Steps to reproduce]:**

1. Navigate to this [experiment page](https://experimenter.services.mozilla.com/nimbus/revert-default-high-contrast-mode-setting-on-macos/summary).
1. Click the History button and observe the behavior.

**[Expected result]:**

* The History page is loaded and all changes made on the experiment are displayed.

**[Actual result]:**

* A 500 server error is displayed.

**[Notes]:**

* There are a number of experiments currently in Stage which have this issue:
  * [https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cfat-14/summary](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cfat-14/summary)
  * [https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cfat-15/summary](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cfat-15/summary)
  * [https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cfat-16/summary](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/cfat-16/summary)

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3929)

**Comment by jaredlockhart** [comment]
This is fixed in https://github.com/mozilla/experimenter/issues/9554

**Comment by SoftVision-CiprianMuresan** [comment]
For what it's worth, the experiments I linked still reproduce the issue and were not fixed by the change in https://github.com/mozilla/experimenter/issues/9554. Reopening at least for the Prod experiment.

We should fix that one at least with an admin edit if possible. But it's a bad look if an old experiment comes back into scope and its history page does not work.

**Comment by jaredlockhart** [comment]
Wait @SoftVision-CiprianMuresan which ones are still failing?  The ones linked above all seem to be loading?

**Comment by SoftVision-CiprianMuresan** [comment]
All of them load yes and I can see the summary pages, but when I try to access the History page, that's where I still see the 500 error.
Looks like backwards mentions don't work in JIRA, I had logged this as a follow-up to https://mozilla-hub.atlassian.net/browse/EXP-3906 which was partially fixed in https://github.com/mozilla/experimenter/pull/9547.

**Comment by jaredlockhart** [comment]
Oh sorry I was mireading I see, the history page, okay cool thank you I'll take a look 👍
